### ISSUE TITLE
Voting system allowing people to prioritize (Multiple points per user upvote)

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/top-issues-action#94]
> ### Is your feature request related to a problem? Please describe.
> Issue: Github "voting" system is binary: +1 or not.
> 
> We would like to let people express their own preferences. If I think this issue is more important to me than other ones, I would like to claim it.
> 
> We have tested the following system to sort the issues: each participant has 100 credits quarterly and he can put them on the issue(s) he wants to. He can put 100 credits on one issue or allocate it on several issues. The drawback of this method is that we need to do it by hand :(
> 
> ### Describe the solution you'd like
> I don't know if it's possible to parse Github issues' comments, but we could use a system where people would vote with a simple syntax, something like: #My_credits_for_this_issue: 80 The parser might detect the hashtag and its corresponding amount, the user and the date of the comment. This way, it might be possible to establish a ranking based on people priorities. Do you think it's possible?
> 
> I understand that the drawback would be the multiplication of comments but it's already the case in many projects where people are adding "+1" in the comments.
> 
> ### Describe alternatives you've considered
> Doing this by hand in a shared spreadsheet.
> 
> ### Additional context
> _No response_

> ### Is your feature request related to a problem? Please describe.
> Issue: Github "voting" system is binary: +1 or not.
> 
> We would like to let people express their own preferences. If I think this issue is more important to me than other ones, I would like to claim it.
> 
> We have tested the following system to sort the issues: each participant has 100 credits quarterly and he can put them on the issue(s) he wants to. He can put 100 credits on one issue or allocate it on several issues. The drawback of this method is that we need to do it by hand :(
> 
> ### Describe the solution you'd like
> I don't know if it's possible to parse Github issues' comments, but we could use a system where people would vote with a simple syntax, something like: #My_credits_for_this_issue: 80 The parser might detect the hashtag and its corresponding amount, the user and the date of the comment. This way, it might be possible to establish a ranking based on people priorities. Do you think it's possible?
> 
> I understand that the drawback would be the multiplication of comments but it's already the case in many projects where people are adding "+1" in the comments.
> 
> ### Describe alternatives you've considered
> Doing this by hand in a shared spreadsheet.
> 
> ### Additional context
> _No response_

_Originally posted by @anuraghazra in https://github.com/anuraghazra/github-readme-stats/issues/2193_

**Comment by rickstaa** [comment]
@CharlesNepote Thanks for your feature request. I thought of something similar, and I think what you are asking for is possible since the GraphQL API allows the following:
- Check which users have upvoted a given issue in a given period (see https://docs.github.com/en/graphql/reference/enums#reactionorderfield and https://docs.github.com/en/graphql/reference/objects#reaction).
- Parsing the issue comments for such a tag is also possible (see https://docs.github.com/en/graphql/reference/objects#issuecommentconnection).

Unfortunately, implementing such a system as a GitHub action would, I think, not be feasible with the current GraphQL API since this system would scale exponentially with the number of users and issues. This action would, therefore, quickly hit the [GraphQL rate limits](https://docs.github.com/en/graphql/overview/resource-limitations). A way to deal with this would be to run the action in multiple steps while keeping track of the GraphQL cost. Implementing this logic is complicated and would still be inefficient since old data is fetched on each run.

If I would implement this feature, in the form you suggested, I would likely not use a GitHub action but create a [Github application](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps). Doing this would allow me to run a cloud function whenever a user upvotes an issue or only periodically fetch new information. Storing this information in a server database would allow the logic to be run and coded on the server. This setup would allow for a nicer interface to show the most upvoted issues and allow users to assign more points to a given issue. 

Nevertheless, I think implementing such an App would be a significant undertaking and only worth it if a lot of people/companies are interested in such an app and if there were no other alternatives. There are already (paid) feature voting apps for more advanced feature tracking use cases that can integrate with GitHub. To name a few:
- https://sleekplan.com: I use this on my bigger projects.
- https://www.shipright.co/product
- https://www.upvoty.com/pricing
- https://canny.io
- https://usersnap.com/pricing

The reason I created https://github.com/rickstaa/top-issues-action was to have a free, easy to setup way to quickly see issues/feature requests/bugs/PR that were most upvoted. It was meant to be an extension of GitHub's own filtering abilities on the GitHub website.

**Comment by rickstaa** [comment]
@CharlesNepote Having that said, I might implement a GitHub app version if there is enough interest in this feature from the community. 🚀

**Comment by CharlesNepote** [comment]
Thanks a lot for your answer!

> Unfortunately, implementing such a system as a GitHub action would, I think, not be feasible with the current GraphQL API since this system would scale exponentially with the number of users and issues.

Would it be possible to run it only once day or even once a week, to stay below the limits?

**Comment by rickstaa** [comment]
I suggest we switch to a GitHub App because a GitHub app can be triggered at every reaction that is added. This would allow us to store this information in a database, allowing us to create more complex top issues dashboards like the one you suggested.

**Comment by rickstaa** [comment]
Closing this as I currently do not have the time to implement a GitHub App version of this action.
